import { Link } from 'react-router-dom'; 

const Logo = () => {
  return (
    <Link to='/'>
        <button
            className="flex items-center gap-3 cursor-pointer flex-shrink-0"
            aria-label="SongVault home"
        >
            {/* Logo generated by Google Gemini */}
            <img
                src="/logo.png"
                alt="Audex Logo"
                className="w-20 h-15 rounded-full object-cover"
            />
            <span className="font-['Bebas_Neue'] text-[42px] tracking-wider text-[#ddeeff] transition-colors duration-200 hover:text-white"> 
                Aud<span className="text-[#00c8ff]">ex</span>
            </span>
        </button>
    </Link>
  );
};

export default Logo;